name = "Normal theme for M. Kuzmin's portfolio"
license = 'MIT'
licenselink = 'https://github.com/m-kuzmin/m-kuzmin/LICENSE'

demosite = 'https://m-kuzmin.github.io/m-kuzmin'

[author]
name = "M. Kuzmin"
homepage = "m-kuzmin.github.io/m-kuzmin"

